GurkhaWatch/gurkhawatch/urls.py
from django.urls.conf import include
from gurkhawatch import settings
from django.contrib import admin
from django.urls import path, include
from . import views as gurkhawatch_views
from shop import views as shop_views
from carts import views as cart_views
from django.conf.urls.static import static
from django.conf import settings
from blog import views as blog_views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', gurkhawatch_views.home, name='home'),
    path('about/', gurkhawatch_views.about, name='about'),
    path('contact/', gurkhawatch_views.contact, name='contact'),
    path('shop/', shop_views.shop, name='shop'),
    path('cart/', cart_views.cart, name='cart'),
    path('add_cart/<int:product_id>/', cart_views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/',
         cart_views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/',
         cart_views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', cart_views.checkout, name='checkout'),
    path('product-category/<slug:category_slug>/',
         shop_views.shop, name='products_by_category'),
    path('product/<slug:product_slug>/',
         shop_views.product_detail, name='product_detail'),
    path('search/', shop_views.search, name='search'),
    # Orders
    path('orders/', include('orders.urls')),
    path('my-account/', include('accounts.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('submit_review/<int:product_id>/',
         shop_views.submit_review, name='submit_review'),
    path('blog/',
         blog_views.post_list, name='blog'),
    path('blog/<slug:slug>/',
         blog_views.postDetail.as_view(), name='blog_detail'),

    # path('product-category/<slug:slug>/', gurkhawatch_views.category, name='category')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "GurkhaWatch Admin"
admin.site.site_title = "GurkhaWatch Admin Portal"
admin.site.index_title = "Welcome to GurkhaWatch Portal"

GurkhaWatch/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shop, name='shop'),
    # to tell program not to consider search a category
    # path('category/<slug:category_slug>/', views.shop, name='products_by_category'),
    # path('product/<slug:product_slug>/', views.product_detail, name='product_detail'),
    # path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    # path('search/', views.search, name='search'),
    
]

GurkhaWatch/shop/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from tinymce.models import HTMLField
from accounts.models import Account
from django.db.models import Avg, Count
# Create your models here.


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    # description = models.TextField(max_length=500, blank=True)
    description = HTMLField()
    price = models.IntegerField()
    # default = 0, so that it doesn't throw 'NoneType' error when null
    discount_percent = models.FloatField(default=0)
    image = models.ImageField(upload_to='photos/products', )
    stock = models.IntegerField()
    specification_image = models.ImageField(
        upload_to='photos/products/specifications', blank=True)
    specification = models.TextField()
    is_available = models.BooleanField(default=True)
    category = models.ManyToManyField(Category, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.slug])

    def __str__(self):
        return self.product_name

    def discount(self):
        if self.discount_percent > 0:
            discounted_price = self.price - self.price * self.discount_percent / 100
            return discounted_price

    def averageReview(self):
        reviews = ReviewRating.objects.filter(
            product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(
            product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count
    # display manytomany field in the django admin panel

    def get_category(self):
        return ", ".join([str(p) for p in self.category.all()])

    def __unicode__(self):
        return "{0}".format(self.product_name)


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(
        Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

GurkhaWatch/shop/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']


class AddToCart(forms.Form):
    add_to_cart = forms.IntegerField()

    def __init__(self, site_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['add_to_cart'] = forms.IntegerField(widget=forms.NumberInput(
            attrs={'class': 'py-1 font-bold text-sm text-center bg-secondary text-primary outline-none rounded-md transition-all duration-200'}))
        self.fields['add_to_cart'] = forms.IntegerField(widget=forms.NumberInput(
            attrs={'id': 'item-cart-count'}))
        self.fields['add_to_cart'] = forms.IntegerField(widget=forms.NumberInput(
            attrs={'type': 'number'}))
        self.fields['add_to_cart'] = forms.IntegerField(widget=forms.NumberInput(
            attrs={'step': '1'}))
        self.fields['add_to_cart'] = forms.IntegerField(widget=forms.NumberInput(
            attrs={'value': '1'}))

GurkhaWatch/blog/views.py
from django.shortcuts import render
from .models import Post
from django.views import generic
# Create your views here.


def post_list(request):
    post_list = Post.objects.all()
    print("hello")
    context = {
        'post_lists': post_list,
    }
    return render(request, 'blog.html', context)


class postDetail(generic.DetailView):
    model = Post
    template_name = 'single_blog.html'

GurkhaWatch/carts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from carts.models import CartItem
from carts.models import Cart
from orders.forms import OrderForm

from shop.models import Product
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)  # get product
    if request.user.is_authenticated:
        try:
            cart_item = CartItem.objects.get(
                product=product, user=current_user)
            cart_item.quantity += 1  # cart_item.quantity = cart_item.quantity + 1
            cart_item.save()
        except CartItem.DoesNotExist:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            cart_item.save()
        return redirect('cart')
    else:
        try:
            # get cart using cart_id from session
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()

        try:
            cart_item = CartItem.objects.get(product=product, cart=cart)
            cart_item.quantity += 1  # cart_item.quantity = cart_item.quantity + 1
            cart_item.save()
        except CartItem.DoesNotExist:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
            )
            cart_item.save()
        return redirect('cart')


def remove_cart(request, product_id):

    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(
                product=product, user=request.user)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id):

    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        grand_total = 0
        service_charge = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            if cart_item.product.discount_percent > 0:
                total += (cart_item.product.discount() * cart_item.quantity)
            else:
                total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        service_charge = int((10 * round(total, 2))/100)
        grand_total = total + service_charge
    except ObjectDoesNotExist:
        pass  # ignore

    context = {
        "total": total,
        "quantity": quantity,
        "cart_items": cart_items,
        "service_charge": service_charge,
        "grand_total": grand_total,
    }
    return render(request, 'cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        grand_total = 0
        service_charge = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            if cart_item.product.discount_percent > 0:
                total += (cart_item.product.discount() * cart_item.quantity)
            else:
                total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        service_charge = int((10 * round(total, 2))/100)
        grand_total = total + service_charge
    except ObjectDoesNotExist:
        pass

    context = {
        "total": total,
        "quantity": quantity,
        "cart_items": cart_items,
        "service_charge": service_charge,
        "grand_total": grand_total,
        "form": OrderForm,

    }
    return render(request, 'checkout.html', context)

GurkhaWatch/category/views.py
from django.shortcuts import render

# Create your views here.

GurkhaWatch/shop/views.py
from django.core import paginator
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from .models import Product, ReviewRating, ProductGallery
from category.models import Category
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from carts.models import CartItem
from carts.views import _cart_id
from .forms import AddToCart, ReviewForm
from orders.models import OrderProduct
# Create your views here.


def shop(request, category_slug=None):
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(
            category=categories, is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True)
        paginator = Paginator(products, 12)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    context = {
        'products': paged_products,
        'product_count': product_count,
    }
    return render(request, 'shop.html', context)

# product detail view


def product_detail(request, product_slug):
    if request.method == 'GET':
        try:
            single_product = Product.objects.get(slug=product_slug)
            in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(
                request), product=single_product).exists()

        except Exception as e:
            raise e

        if request.user.is_authenticated:
            try:
                orderproduct = OrderProduct.objects.filter(
                    user=request.user, product_id=single_product.id).exists()
            except OrderProduct.DoesNotExist:
                orderproduct = None
        else:
            orderproduct = None

        # Get the reviews
        reviews = ReviewRating.objects.filter(
            product_id=single_product.id, status=True)

        # get the product gallery
        product_gallery = ProductGallery.objects.filter(
            product_id=single_product.id)

        # send GET request from the add to cart button
        add_to_cart_input_field = AddToCart(request.GET)
        if add_to_cart_input_field.is_valid():
            cart_item = CartItem()
            cart_item.quantity = add_to_cart_input_field.cleaned_data.get(
                'add_to_cart')

        context = {
            'single_product': single_product,
            'in_cart': in_cart,
            'orderproduct': orderproduct,
            'reviews': reviews,
            'product_gallery': product_gallery,
        }
        return render(request, 'single_product.html', context)


'''
def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug = product_slug)
    except Exception as e:
        raise e
    
    context = {
        'single_product':single_product
    }
    return render(request, 'single_product.html', context)

'''


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(
                Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
    context = {
        'products': products,
        'product_count': product_count,
    }
    return render(request, 'shop.html', context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == "POST":
        try:
            reviews = ReviewRating.objects.get(
                user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(
                request, 'Thank you! your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                # messages.success(
                #     request, ' Thank you! your review has been submitted.')
                return redirect(url)

GurkhaWatch/templates/about.html
{% extends "base.html" %}

{% block head %}
<title>About Us - Gurkha Watch</title>
{% endblock head %}

{% block content %}
<!-- About us start -->
<div class="bg-primary2 text-secondary">
  <div class="h-80 max-w-screen-2xl my-4 mx-auto px-4 flex flex-col justify-center items-center">
    <p class="text-4xl font-bold mb-2">GURKHA WATCH</p>
    <p class="text-2xl font-medium">ABOUT US</p>
  </div>
  <div class="bg-primary3 text-secondary">
    <div class="max-w-screen-2xl mx-auto px-4 py-8 text-sm leading-relaxed font-jura">
      <p>
        Gurkha Watch is a timepiece with technological masterwork and
        ingenious mechanism that symbolizes over 2000 years of bravery and
        acts of extreme valour that lionhearted Gurkha soldiers have shown
        in several war theatres and peacekeeping missions. It is an emblem
        of the Gurkhas-globally known as "The Bravest of the Brave" - who
        have laughed to greet every hardship, remained uncomplaining to
        endure hunger, thirst and wounds, and faced tougher to toughest wars
        without fear. And this watch is for the Gurkha veterans and their
        families who sacrificed their valuable family moments for The Crown
        and mankind that never returned.
      </p>
      <br />
      <p>
        The year 2015 completed the 200 years of Gurkha service to the
        Crown. And this year also marked decades of Gurkhas' service in
        peacekeeping operations around the world. To commemorate their
        service and sacrifice, we, Gurkha Jewellers UK, produced and
        introduced 200 pieces of Khukuri Cross Gurkha watches in UK. The
        first edition of these watches made a big-bang market penetration in
        the UK, and secured quickest sale in the country, which is home to
        millions of Ex-British soldiers.
      </p>
      <br />
      <p>
        We are now venturing to introduce more quintessential watches that
        combine style, elegance and history.
      </p>
    </div>
  </div>
</div>
<!-- About us end -->
{% endblock content %}

GurkhaWatch/templates/accessories.html
{% extends "base.html" %}

{% block head %}
<title>Accessories</title>
<style>
    .blog-card:hover {
        box-shadow: 0px 0px 5px 0px rgb(0 0 0 / 80%);
    }
</style>
{% endblock head %}

{% block content %}


{% endblock content %}

GurkhaWatch/templates/blog.html
{% extends "base.html" %}

{% block head %}
<title>Blog - Gurkha Watch</title>
<style>
  .blog-card:hover {
    box-shadow: 0px 0px 5px 0px rgb(0 0 0 / 80%);
  }
</style>
{% endblock head %}

{% block content %}
<!-- Blog start -->
<div class="bg-primary2 text-secondary">
  <div class="max-w-screen-2xl my-4 mx-auto px-4 py-6">
    <p class="mb-1 text-xl font-bold text-center">BLOG</p>
    <p class="text-sm text-secondary3 text-center">Welcome to our blog!</p>
  </div>
  <div class="bg-primary2 text-secondary">
    <div class="max-w-screen-2xl mx-auto px-4">
      <div class="lg:px-56 py-8 flex justify-end">
        <select name="sorting" class="px-3 py-1 bg-primary5 text-sm rounded-md focus:outline-none cursor-pointer"
          style="padding-inline-end: 1rem;">
          <option selected>Sorting</option>
        </select>
      </div>
      <div class="lg:px-56 grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 text-secondary3">
        {% for post in post_lists %}
        <a href="{% url 'blog_detail' post.slug %}" class="blog-card p-4 bg-primary3 transition-all">
          <p class="font-bold">{{post.title}}</p>
          <div class="h-px w-1/6 my-3 bg-secondary3"></div>
          <p class="text-xs">{{post.content|slice:":200"}}
          </p>
          <p class="my-3 text-xs">{{post.created_on}}</p>
          <div class="h-24 w-full">
            <img src="{{post.blog_image.url}}" alt="{{object.title}}" class="w-full h-full object-cover">
          </div>
        </a>
        {% endfor %}
      </div>
      <div class="lg:px-56 pt-10 pb-14 flex justify-between">
        <a href="#!" class="fa-stack">
          <i class="fas fa-circle fa-stack-2x"></i>
          <i class="fas fa-angle-left fa-stack-1x text-primary"></i>
        </a>
        <a href="#1" class="fa-stack">
          <i class="fas fa-circle fa-stack-2x"></i>
          <i class="fas fa-angle-right fa-stack-1x text-primary"></i>
        </a>
      </div>
    </div>
  </div>
</div>
<!-- Blog end -->
{% endblock content %}

GurkhaWatch/templates/confirmation.html
{% extends "base.html" %}

{% block head %}
<title>Payment Status</title>
{% endblock head %}

{% block content %}
<div class="bg-primary2 text-secondary">
    <div class="max-w-screen-lg mx-auto mt-4 mb-8 px-4">
        {% if payment_status == 'success' %}
        <p class="mb-2 text-lg font-bold">Order Confirmed</p>
        <p>Your order is confirmed with order number: <span>{{order_number}}</span></p>
        <p>Current Order Status: <span>{{order_status}}</span></p>
        <a href="{% url 'shop' %}"
            class="inline-block mt-6 px-4 py-1 bg-secondary hover:bg-secondary4 text-primary rounded-md font-bold transition-all">Continue
            Shopping</a>
        {% else %}
        <p>Something went wrong, Please try again!</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

GurkhaWatch/templates/index.html
{% extends "base.html" %}
{% load mathfilters %}

{% block head %}
<title>Homepage - Gurkha Watch</title>
<style>
  .slick-dots {
    position: static;
  }

  .carousel-slide {
    height: 40vh;
  }

  .carousel-overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.6);
  }

  @media (min-width: 640px) {
    .carousel-slide {
      height: 50vh;
    }
  }

  @media (min-width: 768px) {
    .carousel-overlay {
      background-color: rgba(0, 0, 0, 0.3);
    }
  }

  @media (min-width: 1024px) {
    .carousel-slide-content {
      background-position: top 0 right 10rem;
    }
  }

  @media (min-width: 1280px) {
    .carousel-slide-content {
      background-position: top 0 right 16rem;
    }
  }
</style>
{% endblock head %}

{% block content %}
<!-- Carousel start -->
<div class="bg-primary2">
  <div class="max-w-screen-2xl mt-4 mx-auto px-4 main-carousel" style="margin-bottom: 0;">
    {% for item in sliders %}
    <div class="carousel-slide bg-primary4 text-secondary">
      <div class="carousel-slide-content h-full w-full relative bg-no-repeat bg-right bg-contain"
        style="background-image: url('{{item.slider_product_image.url}}');">
        <div class="carousel-overlay">
          <div
            class="h-full w-full sm:w-3/5 lg:w-2/4 p-3 lg:pl-64 flex flex-col justify-center items-center font-montserrat">
            <h2 class="mb-3 lg:mb-4 text-3xl lg:text-4xl font-semibold text-center">{{item.slider_product_name|upper}}
            </h2>
            <div class="mb-2 lg:mb-3 text-secondary2 uppercase text-center" style="font-size: 0.6rem;">
              {{item.slider_description|safe}}
            </div>
            <div class="flex items-center space-x-4">
              <div class="text-right">
                <p class="mb-1 text-golden" style="font-size: 0.5rem;">STARTING FROM</p>
                {% if item.slider_product_name.discount_percent > 0 %}
                <p class="text-secondary3 leading-none line-through">AU
                  ${{item.slider_product_name.price|div:100|stringformat:'.2f'}}</p>
                <p class="leading-tight">AU ${{item.slider_product_name.discount|div:100|stringformat:'.2f'}}</p>
                {% else %}
                <p class="text-secondary3 leading-none">AU
                  ${{item.slider_product_name.price|div:100|stringformat:'.2f'}}</p>
                {% endif %}
              </div>
              <a href="{{item.slider_product_name.get_url}}"
                class="py-1 px-2 text-xs text-golden hover:text-secondary hover:bg-golden border border-golden rounded-md transition-all duration-500">
                PRODUCT INFO
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<!-- Carousel end -->

<!-- Collection start -->
<div class="bg-primary2 text-secondary">
  <div class="max-w-screen-2xl mx-auto px-4 pt-6">
    <p class="mb-4 text-center">OUR COLLECTION</p>
    <div class="collection-carousel">
      {% for collection in links %}
      <div class="px-3">
        <a href="{{collection.get_url}}" class="h-72 overflow-hidden block relative">
          {% if collection.category_image %}
          <img src="{{collection.category_image.url}}" alt="{{collection.category_name}}"
            class="h-full w-full object-cover transform hover:scale-110 transition duration-700" />
          {% endif %}
          <div class="absolute bottom-4 left-4 font-jura text-secondary">
            <h2 class="text-xl font-semibold">{{collection.category_name|upper}}</h2>
            <p class="text-sm text-secondary2">{{collection.product_set.count}} ITEMS</p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<!-- Collection end -->

<!-- Best selling start -->
<div class="bg-primary2 text-secondary">
  <div class="max-w-screen-2xl mx-auto px-4 pt-6 pb-4">
    <div class="mb-4 flex items-center space-x-3">
      <span>BEST SELLING PRODUCTS</span>
      <span class="h-0.5 bg-secondary2 flex-grow rounded-sm"></span>
    </div>
    <div class="best-selling-carousel">
      {% for collection in collections %}
      {% for best_selling_product in best_selling_products %}
      <div class="p-3">
        <div class="relative">
          {% if best_selling_product.discount_percent > 0 %}
          <span
            class="px-1.5 py-0.5 absolute top-0 left-0 text-xs transform -translate-x-1 -translate-y-1/2 bg-red-500 rounded-md"
            style="z-index: 100;">
            {{best_selling_product.discount_percent|floatformat}}% OFF
          </span>
          {% endif %}
          {% if best_selling_product.stock <= 0 %} <span
            class="px-2 py-1 absolute top-1/3 left-1/2 text-xs text-center font-bold text-red-500 border uppercase border-red-500 transform -rotate-12 -translate-x-1/2 rounded-md"
            style="z-index: 100;">
            Out Of Stock
            </span>
            {% endif %}
            <a href="{{best_selling_product.get_url}}" class="h-60 mb-2 block overflow-hidden">
              <img src="{{best_selling_product.image.url}}" alt="{{best_selling_product.product_name}}"
                class="h-full w-full object-cover transform hover:rotate-30 hover:scale-150 transition duration-500">
            </a>
            <p class="text-golden text-center text-xs">{{collection.category_name|upper}}</p>
            <a href="{{best_selling_product.get_url}}"
              class="block text-secondary text-center text-sm transition-all hover:text-secondary3">{{best_selling_product.product_name|upper}}</a>
            <div class="h-0.5 my-1 bg-secondary2"></div>
            <div class="flex justify-center items-center space-x-2">
              {% if best_selling_product.discount_percent > 0 %}
              <p class="text-secondary3 text-center text-sm line-through">AU
                ${{best_selling_product.price|div:100|stringformat:'.2f'}}</p>
              <p class="text-secondary text-center text-sm">AU
                ${{best_selling_product.discount|div:100|stringformat:'.2f'}}</p>
              {% else %}
              <p class="text-secondary text-center text-sm">AU
                ${{best_selling_product.price|div:100|stringformat:'.2f'}}
                {% endif %}
              </p>
            </div>
        </div>
      </div>
      {% endfor %}
      {% endfor %}
    </div>
  </div>
</div>
<!-- Best selling end -->
{% endblock content %}

{% block scripts %}
<script type="text/javascript">
  $(document).ready(function () {
    $(".main-carousel").slick({
      dots: true,
      arrows: false,
      fade: false,
      inifinite: true,
      speed: 1000,
      slidesToShow: 1,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 3000,
    });

    $(".collection-carousel").slick({
      dots: false,
      arrows: false,
      infinite: true,
      speed: 500,
      slidesToShow: 4,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 2000,
      responsive: [{
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
          infinite: true,
        },
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
          infinite: true,
        },
      },
      {
        breakpoint: 640,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
        },
      },
      ],
    });

    $(".best-selling-carousel").slick({
      dots: false,
      arrows: false,
      infinite: true,
      speed: 500,
      slidesToShow: 5,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 2500,
      responsive: [{
        breakpoint: 1024,
        settings: {
          slidesToShow: 4,
          slidesToScroll: 1,
          infinite: true,
        },
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
          infinite: true,
        },
      },
      {
        breakpoint: 640,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
          infinite: true,
        },
      },
      {
        breakpoint: 500,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
        },
      },
      ],
    });
  });
</script>
{% endblock scripts %}

GurkhaWatch/templates/upcoming_watches.html
<p>These are the upcoming watches</p>